[package]
name = "caller"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.1"
hex = { version = "0.4", default-features = false, features = ["alloc"]}

[build-dependencies]
ckb-gen-types = "0.114.0"
